[project]
name = "my-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "morteza", email = "kashani.morteza@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2,<3",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
