"""initial schema

Revision ID: 1c6a2d1c9c81
Revises: 
Create Date: 2026-09-12 05:29:14.115615

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6a2d1c9c81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_users_name')
    )
    op.create_table('account_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_account_groups_user_id_name')
    )
    op.create_index(op.f('ix_account_groups_user_id'), 'account_groups', ['user_id'], unique=False)
    op.create_table('action_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_action_groups_user_id_name')
    )
    op.create_index(op.f('ix_action_groups_user_id'), 'action_groups', ['user_id'], unique=False)
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_brokers_user_id_name')
    )
    op.create_index(op.f('ix_brokers_user_id'), 'brokers', ['user_id'], unique=False)
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('decimal_digits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_currencies_user_id_code')
    )
    op.create_index(op.f('ix_currencies_user_id'), 'currencies', ['user_id'], unique=False)
    op.create_table('instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trading_platform_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_instances_user_id_name')
    )
    op.create_index(op.f('ix_instances_trading_platform_id'), 'instances', ['trading_platform_id'], unique=False)
    op.create_index(op.f('ix_instances_user_id'), 'instances', ['user_id'], unique=False)
    op.create_table('partial_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_partial_groups_user_id_name')
    )
    op.create_index(op.f('ix_partial_groups_user_id'), 'partial_groups', ['user_id'], unique=False)
    op.create_table('trailing_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_trailing_groups_user_id_name')
    )
    op.create_index(op.f('ix_trailing_groups_user_id'), 'trailing_groups', ['user_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('base_currency_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['account_groups.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'broker_id', 'instance_id', name='uq_accounts_group_broker_instance'),
    sa.UniqueConstraint('name', name='uq_accounts_name')
    )
    op.create_index(op.f('ix_accounts_base_currency_id'), 'accounts', ['base_currency_id'], unique=False)
    op.create_index(op.f('ix_accounts_broker_id'), 'accounts', ['broker_id'], unique=False)
    op.create_index(op.f('ix_accounts_group_id'), 'accounts', ['group_id'], unique=False)
    op.create_index(op.f('ix_accounts_instance_id'), 'accounts', ['instance_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('point_size', sa.Float(), nullable=False),
    sa.Column('digits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_id', 'symbol', name='uq_assets_broker_id_symbol')
    )
    op.create_index(op.f('ix_assets_broker_id'), 'assets', ['broker_id'], unique=False)
    op.create_table('partial_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('profit_percentage', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close_percentage', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_partial_rules_name'),
    sa.UniqueConstraint('partial_group_id', 'profit_percentage', name='uq_partial_rules_group_profit')
    )
    op.create_index(op.f('ix_partial_rules_partial_group_id'), 'partial_rules', ['partial_group_id'], unique=False)
    op.create_table('trailing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('trigger_percentage', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('take_profit_adjustment', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_loss_adjustment', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_trailing_rules_name'),
    sa.UniqueConstraint('trailing_group_id', 'trigger_percentage', name='uq_trailing_rules_group_trigger')
    )
    op.create_index(op.f('ix_trailing_rules_trailing_group_id'), 'trailing_rules', ['trailing_group_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('action_group_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('risk_by_reward', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], ),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_group_id', 'name', name='uq_actions_group_name')
    )
    op.create_index(op.f('ix_actions_account_id'), 'actions', ['account_id'], unique=False)
    op.create_index(op.f('ix_actions_action_group_id'), 'actions', ['action_group_id'], unique=False)
    op.create_index(op.f('ix_actions_asset_id'), 'actions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_actions_partial_group_id'), 'actions', ['partial_group_id'], unique=False)
    op.create_index(op.f('ix_actions_trailing_group_id'), 'actions', ['trailing_group_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trading_platform_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('action_group_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('profit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_executed', sa.Boolean(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('base_tp', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_sl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('real_tp', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('real_sl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], ),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], ),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], ),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_positions_name')
    )
    op.create_index(op.f('ix_positions_account_id'), 'positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_positions_action_group_id'), 'positions', ['action_group_id'], unique=False)
    op.create_index(op.f('ix_positions_action_id'), 'positions', ['action_id'], unique=False)
    op.create_index(op.f('ix_positions_broker_id'), 'positions', ['broker_id'], unique=False)
    op.create_index(op.f('ix_positions_partial_group_id'), 'positions', ['partial_group_id'], unique=False)
    op.create_index(op.f('ix_positions_trading_platform_id'), 'positions', ['trading_platform_id'], unique=False)
    op.create_index(op.f('ix_positions_trailing_group_id'), 'positions', ['trailing_group_id'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_trailing_group_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_trading_platform_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_partial_group_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_broker_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_action_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_action_group_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_account_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_actions_trailing_group_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_partial_group_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_asset_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_group_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_account_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_trailing_rules_trailing_group_id'), table_name='trailing_rules')
    op.drop_table('trailing_rules')
    op.drop_index(op.f('ix_partial_rules_partial_group_id'), table_name='partial_rules')
    op.drop_table('partial_rules')
    op.drop_index(op.f('ix_assets_broker_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_accounts_instance_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_group_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_broker_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_base_currency_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_trailing_groups_user_id'), table_name='trailing_groups')
    op.drop_table('trailing_groups')
    op.drop_index(op.f('ix_partial_groups_user_id'), table_name='partial_groups')
    op.drop_table('partial_groups')
    op.drop_index(op.f('ix_instances_user_id'), table_name='instances')
    op.drop_index(op.f('ix_instances_trading_platform_id'), table_name='instances')
    op.drop_table('instances')
    op.drop_index(op.f('ix_currencies_user_id'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_brokers_user_id'), table_name='brokers')
    op.drop_table('brokers')
    op.drop_index(op.f('ix_action_groups_user_id'), table_name='action_groups')
    op.drop_table('action_groups')
    op.drop_index(op.f('ix_account_groups_user_id'), table_name='account_groups')
    op.drop_table('account_groups')
    op.drop_table('users')
    op.drop_table('trading_platforms')
    # ### end Alembic commands ###
