"""The shared Entity base: one strict Field contract for every Entity."""

from collections.abc import Iterator
from contextlib import contextmanager
from contextvars import ContextVar
from typing import Annotated, Any

from pydantic import ConfigDict, TypeAdapter
from sqlalchemy.orm import declared_attr
from sqlmodel import SQLModel

from model.core.declaration import FieldDeclaration
from model.core.diagnostics import strictly
from model.core.foundation import Foundation, reconstructing
from model.core.metadata import validate_entity
from model.core.naming import entity_name, field_name
from model.core.types import python_type

_internal: ContextVar[bool] = ContextVar("entity_internal", default=False)
_STRICT = ConfigDict(strict=True, hide_input_in_errors=True)


@contextmanager
def _internal_state() -> Iterator[None]:
    """Mark work that sets Field values the Entity has already checked."""
    token = _internal.set(True)
    try:
        yield
    finally:
        _internal.reset(token)


_DECLARED: dict[type, dict[str, FieldDeclaration]] = {}
_ADAPTERS: dict[type, dict[str, TypeAdapter[Any]]] = {}


def _declared(entity: type[Entity]) -> dict[str, FieldDeclaration]:
    if entity not in _DECLARED:
        _DECLARED[entity] = {
            field_name(field.name): field for field in entity.declaration.fields
        }
    return _DECLARED[entity]


def _adapters(entity: type[Entity]) -> dict[str, TypeAdapter[Any]]:
    if entity not in _ADAPTERS:
        _ADAPTERS[entity] = {
            name: TypeAdapter(
                Annotated[info.annotation, *info.metadata], config=_STRICT
            )
            for name, info in entity.model_fields.items()
        }
    return _ADAPTERS[entity]


def _realization_problems(entity: type[Entity]) -> list[str]:
    declaration = entity.declaration
    name = entity.__name__
    problems: list[str] = []
    if name != entity_name(declaration.name):
        problems.append(
            f"{name}: the unit is not named {entity_name(declaration.name)}."
        )
    expected = [field_name(field.name) for field in declaration.fields]
    if list(entity.model_fields) != expected:
        problems.append(
            f"{name}: Fields {list(entity.model_fields)} differ from the Declaration {expected}."
        )
        return problems
    for field in declaration.fields:
        where = f"{name}.{field.name}"
        info = entity.model_fields[field_name(field.name)]
        realization = python_type(field.type)
        optional = field.nullable or field.value_generation is not None
        if info.annotation != (realization | None if optional else realization):
            problems.append(
                f"{where}: the annotation differs from the {field.type} Type."
            )
        required = (
            not field.nullable
            and not field.has_default
            and field.value_generation is None
        )
        if info.is_required() != required:
            problems.append(f"{where}: the requirement differs from the Declaration.")
        elif not required:
            wanted = field.default if field.has_default else None
            if info.default != wanted or info.default_factory is not None:
                problems.append(f"{where}: the default differs from the Declaration.")
        if info.description != field.description:
            problems.append(f"{where}: the description differs from the Declaration.")
        size = next(
            (m.max_length for m in info.metadata if hasattr(m, "max_length")), None
        )
        if size != field.constraints.get("size"):
            problems.append(f"{where}: the size differs from the Declaration.")
    return problems


class Entity(Foundation, SQLModel):
    """Base of every Entity: strict, atomic, and identical on every construction."""

    model_config = ConfigDict(  # pyright: ignore[reportAssignmentType]
        strict=True, extra="forbid", hide_input_in_errors=True
    )

    @declared_attr.directive
    def __tablename__(cls) -> str:  # pyright: ignore[reportIncompatibleVariableOverride]
        return cls.__name__

    def __init__(self, **data: Any) -> None:
        if _internal.get():
            super().__init__(**data)
            return
        entity = type(self)
        with _internal_state():
            strictly(lambda: entity.model_validate(data))
            for name, field in _declared(entity).items():
                supplied = data.get(name) is not None
                if (
                    field.value_generation is not None
                    and supplied
                    and not reconstructing()
                ):
                    raise ValueError(
                        f"{entity.__name__}.{field.name} is generated by its owner and cannot be supplied."
                    )
            super().__init__(**data)

    def __setattr__(self, name: str, value: Any) -> None:
        entity = type(self)
        if _internal.get() or name not in entity.model_fields:
            super().__setattr__(name, value)
            return
        field = _declared(entity)[name]
        if field.immutable:
            raise ValueError(f"{entity.__name__}.{field.name} is immutable.")
        checked = strictly(lambda: _adapters(entity)[name].validate_python(value))
        super().__setattr__(name, checked)

    @classmethod
    def __pydantic_init_subclass__(cls, **kwargs: Any) -> None:
        super().__pydantic_init_subclass__(**kwargs)
        validate_entity(cls.declaration)
        problems = _realization_problems(cls)
        if problems:
            raise ValueError(
                "Entity differs from its Declaration:\n- " + "\n- ".join(problems)
            )
