"""Strict Field value contract shared by every Entity."""

from datetime import UTC
from typing import Annotated, Any

from pydantic import AfterValidator, AwareDatetime
from sqlmodel.main import SQLModelConfig

from .declaration import ValueGeneration
from .foundation import Foundation

UtcDatetime = Annotated[
    AwareDatetime, AfterValidator(lambda value: value.astimezone(UTC))
]
"""A timezone-aware datetime, always held in UTC."""


class EntityBase(Foundation):
    """Applies the same strict Field contract to construction, JSON, and assignment.

    An Auto Increment Field stays pending (None) until its owner assigns it once.
    """

    model_config = SQLModelConfig(
        strict=True, extra="forbid", validate_assignment=True, hide_input_in_errors=True
    )

    def __init__(self, **data: Any) -> None:
        for declared in self.declaration.fields:
            if (
                declared.value_generation is ValueGeneration.AUTO_INCREMENT
                and data.get(declared.name) is not None
            ):
                raise ValueError(
                    f"{declared.name} is generated by its owner and cannot be supplied"
                )
        super().__init__(**data)

    def __setattr__(self, name: str, value: Any) -> None:
        for declared in self.declaration.fields:
            if (
                declared.name == name
                and declared.immutable
                and getattr(self, name) is not None
            ):
                raise ValueError(f"{name} is immutable once assigned")
        super().__setattr__(name, value)
