"""Bringing the declared starting records into storage.

The definitions say which records the project must contain and in what order
their references resolve. This puts them there: references become the
identifiers the storage assigned, values left to be generated are produced here
rather than declared anywhere, and a second run finds the records already
present instead of making them twice.
"""

from __future__ import annotations

import secrets as random
from dataclasses import dataclass
from typing import Any

from my_model import Entity, InitialRecord, awaits_generation, records_in_resolution_order

from . import mapping
from .operations import Operations

GENERATED_LENGTH = 32


@dataclass(frozen=True, slots=True)
class SeedOutcome:
    """What one seeding run did."""

    stored: int
    already_present: int

    @property
    def total(self) -> int:
        return self.stored + self.already_present


def _generate() -> str:
    """A value the declarations deliberately did not carry."""

    return random.token_urlsafe(GENERATED_LENGTH)


def _resolved_values(
    entity: type[Entity],
    record: InitialRecord,
    assigned: dict[str, list[Any]],
) -> dict[str, Any]:
    """One record's values, with references and generated values filled in.

    A reference in a declaration names a record of the target definition by its
    position among that definition's declarations; here it becomes whatever
    identifier the storage actually gave that record.
    """

    references = entity.relationship_fields()
    values: dict[str, Any] = {}
    for name, value in record.values.items():
        if awaits_generation(value):
            values[name] = _generate()
            continue
        if name in references:
            target = references[name].target
            position = int(value)
            identifiers = assigned.get(target, [])
            if not 1 <= position <= len(identifiers):
                raise ValueError(
                    f"{entity.entity_name} refers to {target} record {position}, "
                    f"which was not stored"
                )
            values[name] = identifiers[position - 1]
            continue
        values[name] = value
    return values


def _already_stored(operations: Operations, entity: type[Entity], values: dict[str, Any]):
    """The stored record this declaration describes, if it is there already."""

    key_fields = mapping.natural_key(entity)
    if not key_fields or not all(field in values for field in key_fields):
        return None
    return operations.read(entity, {field: values[field] for field in key_fields})


def seed(operations: Operations) -> SeedOutcome:
    """Store every declared record, in an order where its references exist.

    Running this again over data that already carries the records changes
    nothing: each declaration is recognised by what makes it that logical
    record, and a value generated by an earlier run is left as it is.
    """

    assigned: dict[str, list[Any]] = {}
    stored = present = 0

    for entity, record in records_in_resolution_order():
        values = _resolved_values(entity, record, assigned)
        key_field = mapping.identifying_field(entity)

        existing = _already_stored(operations, entity, values)
        if existing is not None:
            assigned.setdefault(entity.entity_name, []).append(
                getattr(existing, key_field)
            )
            present += 1
            continue

        created = operations.create(entity, values)
        assigned.setdefault(entity.entity_name, []).append(getattr(created, key_field))
        stored += 1

    return SeedOutcome(stored=stored, already_present=present)


__all__ = ["SeedOutcome", "seed"]
