"""Private base of every Entity: strict Field contracts, Declaration consistency."""

from contextvars import ContextVar
from datetime import date, time
from decimal import Decimal
from types import NoneType
from typing import Any, ClassVar, LiteralString, NoReturn, get_args
from uuid import UUID

from pydantic import AwareDatetime, ValidationError
from pydantic_core import InitErrorDetails, PydanticCustomError
from sqlmodel import SQLModel

from model.core.declaration import Declaration

_PYTHON_TYPES: dict[str, Any] = {
    "string": str,
    "integer": int,
    "float": float,
    "decimal": Decimal,
    "boolean": bool,
    "datetime": AwareDatetime,
    "date": date,
    "time": time,
    "uuid": UUID,
}

reconstructing: ContextVar[bool] = ContextVar("reconstructing", default=False)


def _reject(entity: str, name: str, message: LiteralString) -> NoReturn:
    """Raise a validation error for one Field without echoing any value."""
    detail = InitErrorDetails(
        type=PydanticCustomError("field_contract", message), loc=(name,), input=None
    )
    raise ValidationError.from_exception_data(entity, [detail], hide_input=True)


def _verify(
    entity: str, declaration: Declaration, model_fields: dict[str, Any]
) -> None:
    """Verify that an Entity's Python Fields realize its Declaration exactly."""
    if list(model_fields) != [declared.name for declared in declaration.fields]:
        raise TypeError(f"{entity}: Fields differ from the Declaration in order")
    for declared in declaration.fields:
        info = model_fields[declared.name]
        args = get_args(info.annotation)
        allows_none = NoneType in args
        base = info.annotation
        if allows_none:
            base = next(arg for arg in args if arg is not NoneType)
        generated = declared.value_generation == "auto_increment"
        problem = None
        if base is not _PYTHON_TYPES[declared.type]:
            problem = "Type"
        elif allows_none != (declared.nullable or generated):
            problem = "nullability"
        elif generated or (declared.nullable and not declared.has_default):
            if info.is_required() or info.default is not None:
                problem = "pending or absent default"
        elif declared.has_default:
            if (
                info.is_required()
                or info.default != declared.default
                or type(info.default) is not type(declared.default)
            ):
                problem = "Default Value"
        elif not info.is_required():
            problem = "required value"
        limit = next(
            (meta.max_length for meta in info.metadata if hasattr(meta, "max_length")),
            None,
        )
        declared_limit = {} if limit is None else {"max_length": limit}
        if problem is None and dict(declared.constraints) != declared_limit:
            problem = "constraints"
        if problem:
            raise TypeError(
                f"{entity}: Field {declared.name!r} differs from the Declaration "
                f"in {problem}"
            )


class Base(SQLModel):
    """Enforce strict Field contracts and Declaration consistency for every Entity."""

    model_config = SQLModel.model_config | {
        "extra": "forbid",
        "strict": True,
        "validate_assignment": True,
        "allow_inf_nan": False,
        "hide_input_in_errors": True,
    }

    declaration: ClassVar[Declaration]

    def __init__(self, /, **data: Any) -> None:
        if not reconstructing.get():
            for declared in self.declaration.fields:
                supplied = declared.name in data
                if supplied and declared.value_generation == "auto_increment":
                    _reject(
                        type(self).__name__,
                        declared.name,
                        "Field is generated by its owner and cannot be supplied",
                    )
        super().__init__(**data)

    def __setattr__(self, name: str, value: Any) -> None:
        declared = next((f for f in self.declaration.fields if f.name == name), None)
        if declared is not None:
            generated = declared.value_generation == "auto_increment"
            if declared.immutable and not (generated and getattr(self, name) is None):
                _reject(type(self).__name__, name, "Field is immutable once assigned")
            if generated and value is None:
                _reject(type(self).__name__, name, "Field never accepts a null value")
        super().__setattr__(name, value)

    @classmethod
    def __pydantic_init_subclass__(cls, **kwargs: Any) -> None:
        super().__pydantic_init_subclass__(**kwargs)
        if (declaration := getattr(cls, "declaration", None)) is not None:
            _verify(cls.__name__, declaration, cls.model_fields)
