"""Shared fixtures: one minimal valid payload per Domain Definition."""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal

import pytest

from model import (
    Account,
    AccountGroup,
    Action,
    ActionGroup,
    Asset,
    Broker,
    Currency,
    Instance,
    PartialGroup,
    PartialRule,
    Position,
    TradingPlatform,
    TrailingGroup,
    TrailingRule,
    User,
)

SAMPLE_DATA: dict[type, dict[str, object]] = {
    User: {
        "id": 1,
        "name": "Admin",
        "username": "admin",
        "password": "hashed-secret",
        "api_key": "hashed-key",
        "is_active": True,
        "description": None,
    },
    TradingPlatform: {
        "id": 1,
        "name": "MetaTrader 5",
        "code": "metatrader_5",
        "is_active": True,
        "description": None,
    },
    Instance: {
        "id": 1,
        "user_id": 1,
        "trading_platform_id": 1,
        "name": "MetaTrader",
        "ip": "127.0.0.1",
        "username": "test",
        "password": "encrypted-secret",
        "api_key": "encrypted-key",
        "is_active": True,
        "description": None,
    },
    Currency: {
        "id": 1,
        "user_id": 1,
        "code": "USD",
        "symbol": "$",
        "country": "United States",
        "decimal_digits": 2,
        "is_active": True,
        "description": None,
    },
    Broker: {
        "id": 1,
        "name": "FxPro",
        "user_id": 1,
        "is_active": True,
        "description": None,
    },
    Asset: {
        "id": 1,
        "broker_id": 1,
        "symbol": "EUR/USD",
        "category": "Currency",
        "point_size": 0.0001,
        "digits": 5,
        "is_active": True,
        "description": None,
    },
    AccountGroup: {
        "id": 1,
        "user_id": 1,
        "name": "Default",
        "is_active": True,
        "description": None,
    },
    Account: {
        "id": 1,
        "name": "Acc-1",
        "group_id": 1,
        "broker_id": 1,
        "instance_id": 1,
        "base_currency_id": 1,
        "username": "test",
        "password": "encrypted-secret",
        "leverage": 100,
        "balance": Decimal(0),
        "account_type": "CFD",
        "is_active": True,
        "description": None,
    },
    TrailingGroup: {
        "id": 1,
        "user_id": 1,
        "name": "Default",
        "is_active": True,
        "description": None,
    },
    TrailingRule: {
        "id": 1,
        "name": "Trailing Rule 1",
        "trailing_group_id": 1,
        "trigger_percentage": Decimal(50),
        "take_profit_adjustment": None,
        "stop_loss_adjustment": None,
        "is_active": True,
        "description": None,
    },
    PartialGroup: {
        "id": 1,
        "user_id": 1,
        "name": "Default",
        "is_active": True,
        "description": None,
    },
    PartialRule: {
        "id": 1,
        "name": "Partial Rule 1",
        "partial_group_id": 1,
        "profit_percentage": Decimal(50),
        "close_percentage": Decimal(50),
        "is_active": True,
        "description": None,
    },
    ActionGroup: {
        "id": 1,
        "user_id": 1,
        "name": "Default",
        "is_active": True,
        "description": None,
    },
    Action: {
        "id": 1,
        "name": "Default",
        "action_group_id": 1,
        "asset_id": 1,
        "account_id": 1,
        "partial_group_id": 1,
        "trailing_group_id": 1,
        "risk_by_reward": Decimal(1),
        "take_profit": Decimal(1),
        "stop_loss": Decimal(1),
        "is_active": True,
        "description": None,
    },
    Position: {
        "id": 1,
        "user_id": 1,
        "name": "Pos-1",
        "trading_platform_id": 1,
        "broker_id": 1,
        "account_id": 1,
        "trailing_group_id": 1,
        "partial_group_id": 1,
        "action_group_id": 1,
        "action_id": 1,
        "date": datetime(2026, 1, 1, tzinfo=UTC),
        "volume": Decimal(1),
        "profit": Decimal(0),
        "is_executed": False,
        "order_type": "market",
        "base_tp": Decimal(1),
        "base_sl": Decimal(1),
        "real_tp": Decimal(1),
        "real_sl": Decimal(1),
        "is_active": True,
        "description": None,
    },
}


@pytest.fixture(params=list(SAMPLE_DATA.items()), ids=lambda pair: pair[0].__name__)
def domain_sample(request: pytest.FixtureRequest) -> tuple[type, dict[str, object]]:
    """One (Domain Definition class, valid sample payload) pair per parametrized run."""
    return request.param
