"""Marker for a credential value whose generation is delegated to persistence."""

from __future__ import annotations

from typing import Final


class _GenerateSecurely:
    """Sentinel marking a credential field pending secure generation.

    Declared initial data uses this marker instead of a placeholder value for
    a credential field whose actual value is generated by the responsible
    technical Component at insertion time.
    """

    _instance: "_GenerateSecurely | None" = None

    def __new__(cls) -> "_GenerateSecurely":
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __repr__(self) -> str:
        return "GENERATE_SECURELY"


GENERATE_SECURELY: Final = _GenerateSecurely()
