[project]
name = "database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "morteza", email = "kashani.morteza@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1,<2",
    "cryptography>=43",
    "model",
    "pyyaml>=6.0.3",
    "sqlalchemy>=2,<3",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
    "types-pyyaml>=6.0.12.20260906",
]

[tool.uv.sources]
model = { path = "../model", editable = true }
