"""initial structure

Revision ID: 2aedbaeae6f7
Revises: 
Create Date: 2026-09-07 15:16:12.121792+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aedbaeae6f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='AccountGroup.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='AccountGroup.name'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='AccountGroup.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='AccountGroup.description'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='source model: AccountGroup'
    )
    op.create_table('action_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ActionGroup.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='ActionGroup.name'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='ActionGroup.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='ActionGroup.description'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='source model: ActionGroup'
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Asset.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='Asset.name'),
    sa.Column('symbol', sa.String(), autoincrement=False, nullable=False, comment='Asset.symbol'),
    sa.Column('category', sa.String(), autoincrement=False, nullable=False, comment='Asset.category'),
    sa.Column('point_size', sa.Float(), autoincrement=False, nullable=False, comment='Asset.point_size'),
    sa.Column('digits', sa.Integer(), autoincrement=False, nullable=False, comment='Asset.digits'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='Asset.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='Asset.description'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('symbol'),
    comment='source model: Asset'
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Currency.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='Currency.name'),
    sa.Column('code', sa.String(length=3), autoincrement=False, nullable=False, comment='Currency.code'),
    sa.Column('symbol', sa.String(), autoincrement=False, nullable=True, comment='Currency.symbol'),
    sa.Column('country', sa.String(), autoincrement=False, nullable=True, comment='Currency.country'),
    sa.Column('decimal_digits', sa.Integer(), autoincrement=False, nullable=False, comment='Currency.decimal_digits'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='Currency.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='Currency.description'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    comment='source model: Currency'
    )
    op.create_table('partial_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='PartialGroup.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='PartialGroup.name'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='PartialGroup.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='PartialGroup.description'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='source model: PartialGroup'
    )
    op.create_table('trading_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='TradingPlatform.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='TradingPlatform.name'),
    sa.Column('code', sa.String(), autoincrement=False, nullable=False, comment='TradingPlatform.code'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='TradingPlatform.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='TradingPlatform.description'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='source model: TradingPlatform'
    )
    op.create_table('trailing_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='TrailingGroup.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='TrailingGroup.name'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='TrailingGroup.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='TrailingGroup.description'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='source model: TrailingGroup'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='User.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='User.name'),
    sa.Column('username', sa.String(), autoincrement=False, nullable=False, comment='User.username'),
    sa.Column('password', sa.String(), autoincrement=False, nullable=False, comment='User.password'),
    sa.Column('api_key', sa.String(), autoincrement=False, nullable=False, comment='User.api_key'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='User.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='User.description'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='source model: User'
    )
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Broker.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='Broker.name'),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False, comment='Broker.user_id'),
    sa.Column('trading_platform_id', sa.Integer(), autoincrement=False, nullable=False, comment='Broker.trading_platform_id'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='Broker.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='Broker.description'),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], name='fk_brokers_trading_platform_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_brokers_user_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_brokers_user_id_name'),
    comment='source model: Broker'
    )
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brokers_trading_platform_id'), ['trading_platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brokers_user_id'), ['user_id'], unique=False)

    op.create_table('partial_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='PartialRule.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='PartialRule.name'),
    sa.Column('partial_group_id', sa.Integer(), autoincrement=False, nullable=False, comment='PartialRule.partial_group_id'),
    sa.Column('profit_percentage', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='PartialRule.profit_percentage'),
    sa.Column('close_percentage', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='PartialRule.close_percentage'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='PartialRule.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='PartialRule.description'),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], name='fk_partial_rules_partial_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='source model: PartialRule'
    )
    with op.batch_alter_table('partial_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partial_rules_partial_group_id'), ['partial_group_id'], unique=False)

    op.create_table('trailing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='TrailingRule.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='TrailingRule.name'),
    sa.Column('trailing_group_id', sa.Integer(), autoincrement=False, nullable=False, comment='TrailingRule.trailing_group_id'),
    sa.Column('trigger_percentage', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='TrailingRule.trigger_percentage'),
    sa.Column('take_profit_adjustment', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=True, comment='TrailingRule.take_profit_adjustment'),
    sa.Column('stop_loss_adjustment', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=True, comment='TrailingRule.stop_loss_adjustment'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='TrailingRule.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='TrailingRule.description'),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], name='fk_trailing_rules_trailing_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='source model: TrailingRule'
    )
    with op.batch_alter_table('trailing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trailing_rules_trailing_group_id'), ['trailing_group_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Account.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='Account.name'),
    sa.Column('group_id', sa.Integer(), autoincrement=False, nullable=False, comment='Account.group_id'),
    sa.Column('broker_id', sa.Integer(), autoincrement=False, nullable=False, comment='Account.broker_id'),
    sa.Column('base_currency_id', sa.Integer(), autoincrement=False, nullable=False, comment='Account.base_currency_id'),
    sa.Column('username', sa.String(), autoincrement=False, nullable=False, comment='Account.username'),
    sa.Column('password', sa.String(), autoincrement=False, nullable=False, comment='Account.password'),
    sa.Column('leverage', sa.Integer(), autoincrement=False, nullable=False, comment='Account.leverage'),
    sa.Column('balance', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='Account.balance'),
    sa.Column('account_type', sa.String(), autoincrement=False, nullable=False, comment='Account.account_type'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='Account.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='Account.description'),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currencies.id'], name='fk_accounts_base_currency_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], name='fk_accounts_broker_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['account_groups.id'], name='fk_accounts_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='source model: Account'
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_base_currency_id'), ['base_currency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_broker_id'), ['broker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_group_id'), ['group_id'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Action.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='Action.name'),
    sa.Column('action_group_id', sa.Integer(), autoincrement=False, nullable=False, comment='Action.action_group_id'),
    sa.Column('asset_id', sa.Integer(), autoincrement=False, nullable=False, comment='Action.asset_id'),
    sa.Column('account_id', sa.Integer(), autoincrement=False, nullable=False, comment='Action.account_id'),
    sa.Column('partial_group_id', sa.Integer(), autoincrement=False, nullable=False, comment='Action.partial_group_id'),
    sa.Column('trailing_group_id', sa.Integer(), autoincrement=False, nullable=False, comment='Action.trailing_group_id'),
    sa.Column('risk_by_reward', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='Action.risk_by_reward'),
    sa.Column('take_profit', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='Action.take_profit'),
    sa.Column('stop_loss', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='Action.stop_loss'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='Action.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='Action.description'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_actions_account_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], name='fk_actions_action_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_actions_asset_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], name='fk_actions_partial_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], name='fk_actions_trailing_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='source model: Action'
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_action_group_id'), ['action_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_partial_group_id'), ['partial_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_trailing_group_id'), ['trailing_group_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Position.id'),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False, comment='Position.name'),
    sa.Column('trading_platform_id', sa.Integer(), autoincrement=False, nullable=False, comment='Position.trading_platform_id'),
    sa.Column('broker_id', sa.Integer(), autoincrement=False, nullable=False, comment='Position.broker_id'),
    sa.Column('account_id', sa.Integer(), autoincrement=False, nullable=False, comment='Position.account_id'),
    sa.Column('trailing_group_id', sa.Integer(), autoincrement=False, nullable=False, comment='Position.trailing_group_id'),
    sa.Column('partial_group_id', sa.Integer(), autoincrement=False, nullable=False, comment='Position.partial_group_id'),
    sa.Column('action_group_id', sa.Integer(), autoincrement=False, nullable=False, comment='Position.action_group_id'),
    sa.Column('action_id', sa.Integer(), autoincrement=False, nullable=False, comment='Position.action_id'),
    sa.Column('date', sa.DateTime(), autoincrement=False, nullable=False, comment='Position.date'),
    sa.Column('volume', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='Position.volume'),
    sa.Column('profit', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='Position.profit'),
    sa.Column('is_executed', sa.Boolean(), autoincrement=False, nullable=False, comment='Position.is_executed'),
    sa.Column('order_type', sa.String(), autoincrement=False, nullable=False, comment='Position.order_type'),
    sa.Column('base_tp', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='Position.base_tp'),
    sa.Column('base_sl', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='Position.base_sl'),
    sa.Column('real_tp', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='Position.real_tp'),
    sa.Column('real_sl', sa.Numeric(precision=28, scale=10), autoincrement=False, nullable=False, comment='Position.real_sl'),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False, comment='Position.status'),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True, comment='Position.description'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_positions_account_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], name='fk_positions_action_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='fk_positions_action_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], name='fk_positions_broker_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], name='fk_positions_partial_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], name='fk_positions_trading_platform_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], name='fk_positions_trailing_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='source model: Position'
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_action_group_id'), ['action_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_broker_id'), ['broker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_partial_group_id'), ['partial_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_trading_platform_id'), ['trading_platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_trailing_group_id'), ['trailing_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_trailing_group_id'))
        batch_op.drop_index(batch_op.f('ix_positions_trading_platform_id'))
        batch_op.drop_index(batch_op.f('ix_positions_partial_group_id'))
        batch_op.drop_index(batch_op.f('ix_positions_broker_id'))
        batch_op.drop_index(batch_op.f('ix_positions_action_id'))
        batch_op.drop_index(batch_op.f('ix_positions_action_group_id'))
        batch_op.drop_index(batch_op.f('ix_positions_account_id'))

    op.drop_table('positions')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_trailing_group_id'))
        batch_op.drop_index(batch_op.f('ix_actions_partial_group_id'))
        batch_op.drop_index(batch_op.f('ix_actions_asset_id'))
        batch_op.drop_index(batch_op.f('ix_actions_action_group_id'))
        batch_op.drop_index(batch_op.f('ix_actions_account_id'))

    op.drop_table('actions')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_group_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_broker_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_base_currency_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('trailing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trailing_rules_trailing_group_id'))

    op.drop_table('trailing_rules')
    with op.batch_alter_table('partial_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partial_rules_partial_group_id'))

    op.drop_table('partial_rules')
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brokers_user_id'))
        batch_op.drop_index(batch_op.f('ix_brokers_trading_platform_id'))

    op.drop_table('brokers')
    op.drop_table('users')
    op.drop_table('trailing_groups')
    op.drop_table('trading_platforms')
    op.drop_table('partial_groups')
    op.drop_table('currencies')
    op.drop_table('assets')
    op.drop_table('action_groups')
    op.drop_table('account_groups')
    # ### end Alembic commands ###
