"""AccountGroup Entity."""

from typing import ClassVar

from sqlalchemy import UniqueConstraint
from sqlmodel import Field

from my_model.declaration import (
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
)
from my_model.foundation import Foundation


class AccountGroup(Foundation, table=True):
    """Defines an independent group for organizing trading accounts owned by one user.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        user_id (int): Identifies the user who owns the account group.
        name (str): The account group's display name.
        is_active (bool): Indicates whether the account group is active.
        description (str | None): Describes the account group.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="AccountGroup",
        purpose="Defines an independent group for organizing trading accounts owned by one user.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration(
                "user_id",
                FieldType.INTEGER,
                "Identifies the user who owns the account group.",
            ),
            FieldDeclaration(
                "name", FieldType.STRING, "The account group's display name."
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the account group is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the account group.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(("user_id", "name"),),
        references=(Reference("user_id", "User"),),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    __table_args__ = (UniqueConstraint("user_id", "name"),)
    id: int | None = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id")
    name: str
    is_active: bool = True
    description: str | None = None
