"""Account Entity."""

from decimal import Decimal
from typing import ClassVar

from sqlalchemy import UniqueConstraint
from sqlmodel import Field

from my_model.declaration import (
    AtRest,
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
    Sensitivity,
)
from my_model.foundation import Foundation


class Account(Foundation, table=True):
    """Defines a funded trading account through which the system executes trades and launches positions.

    Each Account identifies the trading account and its account-level login credentials, while its selected Instance owns the separate technical connection to the Trading Platform.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        name (str): The account's display name.
        group_id (int): Identifies the account group that contains the account.
        broker_id (int): Identifies the broker that owns the account.
        instance_id (int): Identifies the trading-platform instance used to connect this account.
        base_currency_id (int): Identifies the base currency used by the account.
        username (str): The username identifier used to access the trading account.
        password (str): The credential used to access the trading account.
        leverage (int): Defines the account's leverage multiplier.
        balance (Decimal): Stores the account's current balance.
        account_type (str): Identifies the account model, such as `cfd` or `spread_betting`.
        is_active (bool): Indicates whether the account is active.
        description (str | None): Describes the account.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="Account",
        purpose="Defines a funded trading account through which the system executes trades and launches positions. Each Account identifies the trading account and its account-level login credentials, while its selected Instance owns the separate technical connection to the Trading Platform.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration("name", FieldType.STRING, "The account's display name."),
            FieldDeclaration(
                "group_id",
                FieldType.INTEGER,
                "Identifies the account group that contains the account.",
            ),
            FieldDeclaration(
                "broker_id",
                FieldType.INTEGER,
                "Identifies the broker that owns the account.",
            ),
            FieldDeclaration(
                "instance_id",
                FieldType.INTEGER,
                "Identifies the trading-platform instance used to connect this account.",
            ),
            FieldDeclaration(
                "base_currency_id",
                FieldType.INTEGER,
                "Identifies the base currency used by the account.",
            ),
            FieldDeclaration(
                "username",
                FieldType.STRING,
                "The username identifier used to access the trading account.",
            ),
            FieldDeclaration(
                "password",
                FieldType.STRING,
                "The credential used to access the trading account.",
                sensitivity=Sensitivity.CREDENTIAL,
                at_rest=AtRest.ENCRYPTED,
            ),
            FieldDeclaration(
                "leverage",
                FieldType.INTEGER,
                "Defines the account's leverage multiplier.",
            ),
            FieldDeclaration(
                "balance",
                FieldType.DECIMAL,
                "Stores the account's current balance.",
                required=False,
                default=Decimal(0),
            ),
            FieldDeclaration(
                "account_type",
                FieldType.STRING,
                "Identifies the account model, such as `cfd` or `spread_betting`.",
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the account is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the account.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(
            ("name",),
            ("group_id", "broker_id", "instance_id"),
        ),
        references=(
            Reference("group_id", "AccountGroup"),
            Reference("broker_id", "Broker"),
            Reference("instance_id", "Instance"),
            Reference("base_currency_id", "Currency"),
        ),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
        rules=(
            "Instance credentials authenticate the technical Trading Platform connection; Account credentials authenticate this specific trading account. The same credential must not be duplicated across both Models unless the selected Trading Platform explicitly requires it in both roles.",
        ),
    )
    __table_args__ = (UniqueConstraint("group_id", "broker_id", "instance_id"),)
    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(unique=True)
    group_id: int = Field(foreign_key="accountgroup.id")
    broker_id: int = Field(foreign_key="broker.id")
    instance_id: int = Field(foreign_key="instance.id")
    base_currency_id: int = Field(foreign_key="currency.id")
    username: str
    password: str
    leverage: int
    balance: Decimal = Decimal(0)
    account_type: str
    is_active: bool = True
    description: str | None = None
