"""Action Entity."""

from decimal import Decimal
from typing import ClassVar

from sqlalchemy import UniqueConstraint
from sqlmodel import Field

from my_model.declaration import (
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
)
from my_model.foundation import Foundation


class Action(Foundation, table=True):
    """Defines how a position must be opened.

    An action selects the asset and account and provides the risk, Take Profit, Stop Loss, Partial Group, and Trailing Group settings that determine the position's parameters and execution behavior.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        name (str): The action's display name.
        action_group_id (int): Identifies the action group that contains the action.
        asset_id (int): Identifies the asset traded by the action.
        account_id (int): Identifies the account used to execute the action.
        partial_group_id (int): Identifies the Partial Group used by the action.
        trailing_group_id (int): Identifies the Trailing Group used by the action.
        risk_by_reward (Decimal): Defines the numeric risk-to-reward value used by the action.
        take_profit (Decimal): Defines the Take Profit value used by the action.
        stop_loss (Decimal): Defines the Stop Loss value used by the action.
        is_active (bool): Indicates whether the action is active.
        description (str | None): Describes the action.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="Action",
        purpose="Defines how a position must be opened. An action selects the asset and account and provides the risk, Take Profit, Stop Loss, Partial Group, and Trailing Group settings that determine the position's parameters and execution behavior.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration("name", FieldType.STRING, "The action's display name."),
            FieldDeclaration(
                "action_group_id",
                FieldType.INTEGER,
                "Identifies the action group that contains the action.",
            ),
            FieldDeclaration(
                "asset_id",
                FieldType.INTEGER,
                "Identifies the asset traded by the action.",
            ),
            FieldDeclaration(
                "account_id",
                FieldType.INTEGER,
                "Identifies the account used to execute the action.",
            ),
            FieldDeclaration(
                "partial_group_id",
                FieldType.INTEGER,
                "Identifies the Partial Group used by the action.",
            ),
            FieldDeclaration(
                "trailing_group_id",
                FieldType.INTEGER,
                "Identifies the Trailing Group used by the action.",
            ),
            FieldDeclaration(
                "risk_by_reward",
                FieldType.DECIMAL,
                "Defines the numeric risk-to-reward value used by the action.",
            ),
            FieldDeclaration(
                "take_profit",
                FieldType.DECIMAL,
                "Defines the Take Profit value used by the action.",
            ),
            FieldDeclaration(
                "stop_loss",
                FieldType.DECIMAL,
                "Defines the Stop Loss value used by the action.",
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the action is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the action.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(("action_group_id", "name"),),
        references=(
            Reference("action_group_id", "ActionGroup"),
            Reference("asset_id", "Asset"),
            Reference("account_id", "Account"),
            Reference("partial_group_id", "PartialGroup"),
            Reference("trailing_group_id", "TrailingGroup"),
        ),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    __table_args__ = (UniqueConstraint("action_group_id", "name"),)
    id: int | None = Field(default=None, primary_key=True)
    name: str
    action_group_id: int = Field(foreign_key="actiongroup.id")
    asset_id: int = Field(foreign_key="asset.id")
    account_id: int = Field(foreign_key="account.id")
    partial_group_id: int = Field(foreign_key="partialgroup.id")
    trailing_group_id: int = Field(foreign_key="trailinggroup.id")
    risk_by_reward: Decimal
    take_profit: Decimal
    stop_loss: Decimal
    is_active: bool = True
    description: str | None = None
