"""ActionGroup Entity."""

from typing import ClassVar

from sqlalchemy import UniqueConstraint
from sqlmodel import Field

from my_model.declaration import (
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
)
from my_model.foundation import Foundation


class ActionGroup(Foundation, table=True):
    """Defines an independent grouping for trading actions based on their risk profile, such as high risk, normal risk, or low risk.

    Actions are assigned to these groups so trades can be organized and selected by their intended risk level.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        user_id (int): Identifies the user who owns the action group.
        name (str): The action group's display name.
        is_active (bool): Indicates whether the action group is active.
        description (str | None): Describes the action group.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="ActionGroup",
        purpose="Defines an independent grouping for trading actions based on their risk profile, such as high risk, normal risk, or low risk. Actions are assigned to these groups so trades can be organized and selected by their intended risk level.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration(
                "user_id",
                FieldType.INTEGER,
                "Identifies the user who owns the action group.",
            ),
            FieldDeclaration(
                "name", FieldType.STRING, "The action group's display name."
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the action group is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the action group.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(("user_id", "name"),),
        references=(Reference("user_id", "User"),),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    __table_args__ = (UniqueConstraint("user_id", "name"),)
    id: int | None = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id")
    name: str
    is_active: bool = True
    description: str | None = None
