"""Asset Entity."""

from typing import ClassVar

from sqlalchemy import UniqueConstraint
from sqlmodel import Field

from my_model.declaration import (
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
)
from my_model.foundation import Foundation


class Asset(Foundation, table=True):
    """Defines an asset that can be selected for trading.

    It provides the system with the complete set of available tradable assets and identifies the category of each asset so the system knows exactly what is being traded.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        broker_id (int): Identifies the broker that provides this asset.
        symbol (str): Identifies the tradable asset, such as `EUR/USD`, `XAU/USD`, or `USOil`.
        category (str): Identifies the asset category, such as `Currency`, `Commodity`, or `Cryptocurrency`.
        point_size (float): Stores the size of one point for the asset.
        digits (int): Stores the number of decimal digits used for the asset's price.
        is_active (bool): Indicates whether the asset is active.
        description (str | None): Describes the asset.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="Asset",
        purpose="Defines an asset that can be selected for trading. It provides the system with the complete set of available tradable assets and identifies the category of each asset so the system knows exactly what is being traded.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration(
                "broker_id",
                FieldType.INTEGER,
                "Identifies the broker that provides this asset.",
            ),
            FieldDeclaration(
                "symbol",
                FieldType.STRING,
                "Identifies the tradable asset, such as `EUR/USD`, `XAU/USD`, or `USOil`.",
            ),
            FieldDeclaration(
                "category",
                FieldType.STRING,
                "Identifies the asset category, such as `Currency`, `Commodity`, or `Cryptocurrency`.",
            ),
            FieldDeclaration(
                "point_size",
                FieldType.FLOAT,
                "Stores the size of one point for the asset.",
                required=False,
                default=0.0,
            ),
            FieldDeclaration(
                "digits",
                FieldType.INTEGER,
                "Stores the number of decimal digits used for the asset's price.",
                required=False,
                default=0,
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the asset is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the asset.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(("broker_id", "symbol"),),
        references=(Reference("broker_id", "Broker"),),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    __table_args__ = (UniqueConstraint("broker_id", "symbol"),)
    id: int | None = Field(default=None, primary_key=True)
    broker_id: int = Field(foreign_key="broker.id")
    symbol: str
    category: str
    point_size: float = 0.0
    digits: int = 0
    is_active: bool = True
    description: str | None = None
