"""Broker Entity."""

from typing import ClassVar

from sqlalchemy import UniqueConstraint
from sqlmodel import Field

from my_model.declaration import (
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
)
from my_model.foundation import Foundation


class Broker(Foundation, table=True):
    """Defines a broker supported by the system and identifies the user who owns its configuration without coupling the Broker definition to one Trading Platform.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        name (str): The broker's display name.
        user_id (int): Identifies the user who owns the broker configuration.
        is_active (bool): Indicates whether the broker is active.
        description (str | None): Describes the broker.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="Broker",
        purpose="Defines a broker supported by the system and identifies the user who owns its configuration without coupling the Broker definition to one Trading Platform.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration("name", FieldType.STRING, "The broker's display name."),
            FieldDeclaration(
                "user_id",
                FieldType.INTEGER,
                "Identifies the user who owns the broker configuration.",
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the broker is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the broker.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(("user_id", "name"),),
        references=(Reference("user_id", "User"),),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    __table_args__ = (UniqueConstraint("user_id", "name"),)
    id: int | None = Field(default=None, primary_key=True)
    name: str
    user_id: int = Field(foreign_key="user.id")
    is_active: bool = True
    description: str | None = None
