"""Currency Entity."""

from typing import ClassVar

from sqlalchemy import UniqueConstraint
from sqlmodel import Field

from my_model.declaration import (
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
)
from my_model.foundation import Foundation


class Currency(Foundation, table=True):
    """Defines a currency that can be used by the trading system and identifies its standard code, display symbol, associated country or region, and monetary decimal precision.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        user_id (int): Identifies the user who owns this currency.
        code (str): The currency's standard three-letter code, such as `USD` or `EUR`.
        symbol (str | None): The currency's display symbol, such as `$`, `€`, or `£`.
        country (str | None): Identifies the country or region associated with the currency.
        decimal_digits (int): Defines the number of decimal digits normally used for monetary values in the currency.
        is_active (bool): Indicates whether the currency is active.
        description (str | None): Describes the currency.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="Currency",
        purpose="Defines a currency that can be used by the trading system and identifies its standard code, display symbol, associated country or region, and monetary decimal precision.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration(
                "user_id",
                FieldType.INTEGER,
                "Identifies the user who owns this currency.",
            ),
            FieldDeclaration(
                "code",
                FieldType.STRING,
                "The currency's standard three-letter code, such as `USD` or `EUR`.",
                max_length=3,
            ),
            FieldDeclaration(
                "symbol",
                FieldType.STRING,
                "The currency's display symbol, such as `$`, `€`, or `£`.",
                nullable=True,
                required=False,
            ),
            FieldDeclaration(
                "country",
                FieldType.STRING,
                "Identifies the country or region associated with the currency.",
                nullable=True,
                required=False,
            ),
            FieldDeclaration(
                "decimal_digits",
                FieldType.INTEGER,
                "Defines the number of decimal digits normally used for monetary values in the currency.",
                required=False,
                default=2,
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the currency is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the currency.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(("user_id", "code"),),
        references=(Reference("user_id", "User"),),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    __table_args__ = (UniqueConstraint("user_id", "code"),)
    id: int | None = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id")
    code: str = Field(max_length=3)
    symbol: str | None = None
    country: str | None = None
    decimal_digits: int = 2
    is_active: bool = True
    description: str | None = None
