"""Instance Entity."""

from typing import ClassVar

from sqlalchemy import UniqueConstraint
from sqlmodel import Field

from my_model.declaration import (
    AtRest,
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
    Sensitivity,
)
from my_model.foundation import Foundation


class Instance(Foundation, table=True):
    """Defines a user-owned connection instance through which the system accesses a supported Trading Platform.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        user_id (int): Identifies the user who owns this instance.
        trading_platform_id (int): Identifies the trading platform used by this instance.
        name (str): The instance's display name.
        ip (str | None): Identifies the technical network address used to reach the Trading Platform when required.
        username (str | None): Defines the technical username used to establish the Instance connection when required.
        password (str | None): Defines the technical password used to establish the Instance connection when required.
        api_key (str | None): Defines the technical API credential used to establish the Instance connection when required.
        is_active (bool): Indicates whether the instance is active.
        description (str | None): Describes the instance.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="Instance",
        purpose="Defines a user-owned connection instance through which the system accesses a supported Trading Platform.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration(
                "user_id",
                FieldType.INTEGER,
                "Identifies the user who owns this instance.",
            ),
            FieldDeclaration(
                "trading_platform_id",
                FieldType.INTEGER,
                "Identifies the trading platform used by this instance.",
            ),
            FieldDeclaration("name", FieldType.STRING, "The instance's display name."),
            FieldDeclaration(
                "ip",
                FieldType.STRING,
                "Identifies the technical network address used to reach the Trading Platform when required.",
                nullable=True,
                required=False,
            ),
            FieldDeclaration(
                "username",
                FieldType.STRING,
                "Defines the technical username used to establish the Instance connection when required.",
                nullable=True,
                required=False,
            ),
            FieldDeclaration(
                "password",
                FieldType.STRING,
                "Defines the technical password used to establish the Instance connection when required.",
                nullable=True,
                required=False,
                sensitivity=Sensitivity.CREDENTIAL,
                at_rest=AtRest.ENCRYPTED,
            ),
            FieldDeclaration(
                "api_key",
                FieldType.STRING,
                "Defines the technical API credential used to establish the Instance connection when required.",
                nullable=True,
                required=False,
                sensitivity=Sensitivity.CREDENTIAL,
                at_rest=AtRest.ENCRYPTED,
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the instance is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the instance.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(("user_id", "name"),),
        references=(
            Reference("user_id", "User"),
            Reference("trading_platform_id", "TradingPlatform"),
        ),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
        rules=(
            "The Trading Platform selected through `trading_platform_id` defines which connection fields are required; every field it requires must be present before the Instance can be used.",
        ),
    )
    __table_args__ = (UniqueConstraint("user_id", "name"),)
    id: int | None = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id")
    trading_platform_id: int = Field(foreign_key="tradingplatform.id")
    name: str
    ip: str | None = None
    username: str | None = None
    password: str | None = None
    api_key: str | None = None
    is_active: bool = True
    description: str | None = None
