"""PartialRule Entity."""

from decimal import Decimal
from typing import ClassVar

from sqlalchemy import UniqueConstraint
from sqlmodel import Field

from my_model.declaration import (
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
)
from my_model.foundation import Foundation


class PartialRule(Foundation, table=True):
    """Defines an individual Partial Close rule that tells the system under which condition part of an open position must be closed and how much of its volume must be closed.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        name (str): The partial rule's display name.
        partial_group_id (int): Identifies the partial group that contains the rule.
        profit_percentage (Decimal): Defines the profit percentage that activates the rule.
        close_percentage (Decimal): Defines the percentage of the position closed when the rule is activated.
        is_active (bool): Indicates whether the partial rule is active.
        description (str | None): Describes the partial rule.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="PartialRule",
        purpose="Defines an individual Partial Close rule that tells the system under which condition part of an open position must be closed and how much of its volume must be closed.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration(
                "name", FieldType.STRING, "The partial rule's display name."
            ),
            FieldDeclaration(
                "partial_group_id",
                FieldType.INTEGER,
                "Identifies the partial group that contains the rule.",
            ),
            FieldDeclaration(
                "profit_percentage",
                FieldType.DECIMAL,
                "Defines the profit percentage that activates the rule.",
            ),
            FieldDeclaration(
                "close_percentage",
                FieldType.DECIMAL,
                "Defines the percentage of the position closed when the rule is activated.",
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the partial rule is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the partial rule.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(
            ("name",),
            ("partial_group_id", "profit_percentage"),
        ),
        references=(Reference("partial_group_id", "PartialGroup"),),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    __table_args__ = (UniqueConstraint("partial_group_id", "profit_percentage"),)
    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(unique=True)
    partial_group_id: int = Field(foreign_key="partialgroup.id")
    profit_percentage: Decimal
    close_percentage: Decimal
    is_active: bool = True
    description: str | None = None
