"""PartialGroup Entity."""

from typing import ClassVar

from sqlalchemy import UniqueConstraint
from sqlmodel import Field

from my_model.declaration import (
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
)
from my_model.foundation import Foundation


class PartialGroup(Foundation, table=True):
    """Defines an independent group of rules for managing portions of an open trade.

    Its rules determine how much of the trade volume must be closed when profit or loss reaches specified thresholds.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        user_id (int): Identifies the user who owns the partial group.
        name (str): The partial group's display name.
        is_active (bool): Indicates whether the partial group is active.
        description (str | None): Describes the partial group.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="PartialGroup",
        purpose="Defines an independent group of rules for managing portions of an open trade. Its rules determine how much of the trade volume must be closed when profit or loss reaches specified thresholds.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration(
                "user_id",
                FieldType.INTEGER,
                "Identifies the user who owns the partial group.",
            ),
            FieldDeclaration(
                "name", FieldType.STRING, "The partial group's display name."
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the partial group is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the partial group.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(("user_id", "name"),),
        references=(Reference("user_id", "User"),),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    __table_args__ = (UniqueConstraint("user_id", "name"),)
    id: int | None = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id")
    name: str
    is_active: bool = True
    description: str | None = None
