"""Position Entity."""

from datetime import datetime
from decimal import Decimal
from typing import ClassVar

from sqlmodel import Field

from my_model.declaration import (
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
)
from my_model.foundation import Foundation


class Position(Foundation, table=True):
    """Stores the complete information for every position created by the system.

    It allows the system to identify and track positions that have been opened as well as positions that are still pending execution.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        user_id (int): Identifies the user who owns the position.
        name (str): The position's display name.
        trading_platform_id (int): Identifies the trading platform used to execute the position.
        broker_id (int): Identifies the broker through which the position is executed.
        account_id (int): Identifies the trading account used for the position.
        trailing_group_id (int): Identifies the Trailing Group applied to the position.
        partial_group_id (int): Identifies the Partial Group applied to the position.
        action_group_id (int): Identifies the Action Group associated with the position.
        action_id (int): Identifies the action from which the position is created.
        date (datetime): Stores the position's date and time.
        volume (Decimal): Stores the position's trading volume.
        profit (Decimal): Stores the position's current profit or loss.
        is_executed (bool): Indicates whether the position has been executed.
        order_type (str): Stores the position's order type.
        base_tp (Decimal): Stores the position's initial Take Profit value.
        base_sl (Decimal): Stores the position's initial Stop Loss value.
        real_tp (Decimal): Stores the position's current Take Profit value.
        real_sl (Decimal): Stores the position's current Stop Loss value.
        is_active (bool): Indicates whether the position is active.
        description (str | None): Describes the position.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="Position",
        purpose="Stores the complete information for every position created by the system. It allows the system to identify and track positions that have been opened as well as positions that are still pending execution.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration(
                "user_id",
                FieldType.INTEGER,
                "Identifies the user who owns the position.",
            ),
            FieldDeclaration("name", FieldType.STRING, "The position's display name."),
            FieldDeclaration(
                "trading_platform_id",
                FieldType.INTEGER,
                "Identifies the trading platform used to execute the position.",
            ),
            FieldDeclaration(
                "broker_id",
                FieldType.INTEGER,
                "Identifies the broker through which the position is executed.",
            ),
            FieldDeclaration(
                "account_id",
                FieldType.INTEGER,
                "Identifies the trading account used for the position.",
            ),
            FieldDeclaration(
                "trailing_group_id",
                FieldType.INTEGER,
                "Identifies the Trailing Group applied to the position.",
            ),
            FieldDeclaration(
                "partial_group_id",
                FieldType.INTEGER,
                "Identifies the Partial Group applied to the position.",
            ),
            FieldDeclaration(
                "action_group_id",
                FieldType.INTEGER,
                "Identifies the Action Group associated with the position.",
            ),
            FieldDeclaration(
                "action_id",
                FieldType.INTEGER,
                "Identifies the action from which the position is created.",
            ),
            FieldDeclaration(
                "date", FieldType.DATETIME, "Stores the position's date and time."
            ),
            FieldDeclaration(
                "volume", FieldType.DECIMAL, "Stores the position's trading volume."
            ),
            FieldDeclaration(
                "profit",
                FieldType.DECIMAL,
                "Stores the position's current profit or loss.",
                required=False,
                default=Decimal(0),
            ),
            FieldDeclaration(
                "is_executed",
                FieldType.BOOLEAN,
                "Indicates whether the position has been executed.",
                required=False,
                default=False,
            ),
            FieldDeclaration(
                "order_type", FieldType.STRING, "Stores the position's order type."
            ),
            FieldDeclaration(
                "base_tp",
                FieldType.DECIMAL,
                "Stores the position's initial Take Profit value.",
            ),
            FieldDeclaration(
                "base_sl",
                FieldType.DECIMAL,
                "Stores the position's initial Stop Loss value.",
            ),
            FieldDeclaration(
                "real_tp",
                FieldType.DECIMAL,
                "Stores the position's current Take Profit value.",
            ),
            FieldDeclaration(
                "real_sl",
                FieldType.DECIMAL,
                "Stores the position's current Stop Loss value.",
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the position is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the position.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(("name",),),
        references=(
            Reference("user_id", "User"),
            Reference("trading_platform_id", "TradingPlatform"),
            Reference("broker_id", "Broker"),
            Reference("account_id", "Account"),
            Reference("trailing_group_id", "TrailingGroup"),
            Reference("partial_group_id", "PartialGroup"),
            Reference("action_group_id", "ActionGroup"),
            Reference("action_id", "Action"),
        ),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    id: int | None = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id")
    name: str = Field(unique=True)
    trading_platform_id: int = Field(foreign_key="tradingplatform.id")
    broker_id: int = Field(foreign_key="broker.id")
    account_id: int = Field(foreign_key="account.id")
    trailing_group_id: int = Field(foreign_key="trailinggroup.id")
    partial_group_id: int = Field(foreign_key="partialgroup.id")
    action_group_id: int = Field(foreign_key="actiongroup.id")
    action_id: int = Field(foreign_key="action.id")
    date: datetime
    volume: Decimal
    profit: Decimal = Decimal(0)
    is_executed: bool = False
    order_type: str
    base_tp: Decimal
    base_sl: Decimal
    real_tp: Decimal
    real_sl: Decimal
    is_active: bool = True
    description: str | None = None
