"""TradingPlatform Entity."""

from typing import ClassVar

from sqlmodel import Field

from my_model.declaration import (
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
)
from my_model.foundation import Foundation


class TradingPlatform(Foundation, table=True):
    """Defines a supported trading API standard, such as MetaTrader 5 or Binance, while keeping the system independent of any specific exchange or broker.

    Every trading platform implementation exposes the same application-facing trading functions through a dedicated class, while handling communication with its destination API according to that platform's own mechanism. Additional platform implementations can be added without changing the system's common trading interface.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        name (str): The platform's display name.
        code (str): Identifies the implementation class the application must use for this trading platform, such as `binance` or `metatrader_5`.
        is_active (bool): Indicates whether the platform is active.
        description (str | None): Describes the platform.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="TradingPlatform",
        purpose="Defines a supported trading API standard, such as MetaTrader 5 or Binance, while keeping the system independent of any specific exchange or broker. Every trading platform implementation exposes the same application-facing trading functions through a dedicated class, while handling communication with its destination API according to that platform's own mechanism. Additional platform implementations can be added without changing the system's common trading interface.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration("name", FieldType.STRING, "The platform's display name."),
            FieldDeclaration(
                "code",
                FieldType.STRING,
                "Identifies the implementation class the application must use for this trading platform, such as `binance` or `metatrader_5`.",
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the platform is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the platform.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(("name",),),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(unique=True)
    code: str
    is_active: bool = True
    description: str | None = None
