"""TrailingRule Entity."""

from decimal import Decimal
from typing import ClassVar

from sqlalchemy import UniqueConstraint
from sqlmodel import Field

from my_model.declaration import (
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Reference,
)
from my_model.foundation import Foundation


class TrailingRule(Foundation, table=True):
    """Defines an individual rule within a Trailing Group that tells the system when and how to manage Take Profit and Stop Loss.

    Each rule provides the activation condition and the parameters used to apply the required adjustments.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        name (str): The trailing rule's display name.
        trailing_group_id (int): Identifies the trailing group that contains the rule.
        trigger_percentage (Decimal): Defines the profit percentage of the take-profit target that activates the rule.
        take_profit_adjustment (Decimal | None): Defines the take-profit adjustment applied when the rule is activated.
        stop_loss_adjustment (Decimal | None): Defines the stop-loss adjustment applied when the rule is activated.
        is_active (bool): Indicates whether the trailing rule is active.
        description (str | None): Describes the trailing rule.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="TrailingRule",
        purpose="Defines an individual rule within a Trailing Group that tells the system when and how to manage Take Profit and Stop Loss. Each rule provides the activation condition and the parameters used to apply the required adjustments.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration(
                "name", FieldType.STRING, "The trailing rule's display name."
            ),
            FieldDeclaration(
                "trailing_group_id",
                FieldType.INTEGER,
                "Identifies the trailing group that contains the rule.",
            ),
            FieldDeclaration(
                "trigger_percentage",
                FieldType.DECIMAL,
                "Defines the profit percentage of the take-profit target that activates the rule.",
            ),
            FieldDeclaration(
                "take_profit_adjustment",
                FieldType.DECIMAL,
                "Defines the take-profit adjustment applied when the rule is activated.",
                nullable=True,
                required=False,
            ),
            FieldDeclaration(
                "stop_loss_adjustment",
                FieldType.DECIMAL,
                "Defines the stop-loss adjustment applied when the rule is activated.",
                nullable=True,
                required=False,
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the trailing rule is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the trailing rule.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(
            ("name",),
            ("trailing_group_id", "trigger_percentage"),
        ),
        references=(Reference("trailing_group_id", "TrailingGroup"),),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    __table_args__ = (UniqueConstraint("trailing_group_id", "trigger_percentage"),)
    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(unique=True)
    trailing_group_id: int = Field(foreign_key="trailinggroup.id")
    trigger_percentage: Decimal
    take_profit_adjustment: Decimal | None = None
    stop_loss_adjustment: Decimal | None = None
    is_active: bool = True
    description: str | None = None
