"""User Entity."""

from typing import ClassVar

from sqlmodel import Field

from my_model.declaration import (
    AtRest,
    Declaration,
    FieldDeclaration,
    FieldType,
    Generation,
    GenerationKind,
    Sensitivity,
)
from my_model.foundation import Foundation


class User(Foundation, table=True):
    """Defines an independent user of the system and enables multi-user operation.

    Each user can have a separate set of settings, allowing new users to be added with configurations that remain distinct from those of existing users.

    Attributes:
        id (int | None): Primary Key generated by Auto Increment.
        name (str): The user's display name.
        username (str): The username used to identify the user.
        password (str): The password credential used by the user.
        api_key (str): The API key assigned to the user.
        is_active (bool): Indicates whether the user is active.
        description (str | None): Describes the user.
    """

    declaration: ClassVar[Declaration] = Declaration(
        entity="User",
        purpose="Defines an independent user of the system and enables multi-user operation. Each user can have a separate set of settings, allowing new users to be added with configurations that remain distinct from those of existing users.",
        fields=(
            FieldDeclaration("id", FieldType.INTEGER, "", required=False),
            FieldDeclaration("name", FieldType.STRING, "The user's display name."),
            FieldDeclaration(
                "username", FieldType.STRING, "The username used to identify the user."
            ),
            FieldDeclaration(
                "password",
                FieldType.STRING,
                "The password credential used by the user.",
                sensitivity=Sensitivity.CREDENTIAL,
                at_rest=AtRest.HASH,
            ),
            FieldDeclaration(
                "api_key",
                FieldType.STRING,
                "The API key assigned to the user.",
                sensitivity=Sensitivity.CREDENTIAL,
                at_rest=AtRest.HASH,
            ),
            FieldDeclaration(
                "is_active",
                FieldType.BOOLEAN,
                "Indicates whether the user is active.",
                required=False,
                default=True,
            ),
            FieldDeclaration(
                "description",
                FieldType.STRING,
                "Describes the user.",
                nullable=True,
                required=False,
            ),
        ),
        primary_key=("id",),
        unique=(
            ("name",),
            ("username",),
        ),
        generation=(Generation("id", GenerationKind.AUTO_INCREMENT),),
    )
    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(unique=True)
    username: str = Field(unique=True)
    password: str
    api_key: str
    is_active: bool = True
    description: str | None = None
