"""Create the whole stored structure

Recorded change: 00854df6a0a5
Follows: 
Created: 2026-09-08 12:50:49.196775
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00854df6a0a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The account group's display name."),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the account group.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Implements the AccountGroup definition.',
    info={'definition': 'AccountGroup'}
    )
    op.create_table('action_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The action group's display name."),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the action group.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Implements the ActionGroup definition.',
    info={'definition': 'ActionGroup'}
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The asset's display name."),
    sa.Column('symbol', sa.String(), nullable=False, comment='Identifies the tradable asset, such as EUR/USD, XAU/USD or USOil.'),
    sa.Column('category', sa.String(), nullable=False, comment='The asset category, such as Currency, Commodity or Cryptocurrency.'),
    sa.Column('point_size', sa.Float(), nullable=False, comment='The size of one point for the asset.'),
    sa.Column('digits', sa.Integer(), nullable=False, comment="The number of decimal digits used for the asset's price."),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the asset.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('symbol'),
    comment='Implements the Asset definition.',
    info={'definition': 'Asset'}
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The currency's full name."),
    sa.Column('code', sa.String(length=3), nullable=False, comment="The currency's standard three-letter code, such as USD or EUR."),
    sa.Column('symbol', sa.String(), nullable=True, comment="The currency's display symbol, such as $, € or £."),
    sa.Column('country', sa.String(), nullable=True, comment='The country or region associated with the currency.'),
    sa.Column('decimal_digits', sa.Integer(), nullable=False, comment='The number of decimal digits monetary values normally use.'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the currency.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    comment='Implements the Currency definition.',
    info={'definition': 'Currency'}
    )
    op.create_table('partial_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The partial group's display name."),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the partial group.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Implements the PartialGroup definition.',
    info={'definition': 'PartialGroup'}
    )
    op.create_table('trading_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The platform's display name."),
    sa.Column('code', sa.String(), nullable=False, comment='Identifies the implementation the application must use for this platform, such as binance or metatrader_5.'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the platform.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Implements the TradingPlatform definition.',
    info={'definition': 'TradingPlatform'}
    )
    op.create_table('trailing_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The trailing group's display name."),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the trailing group.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Implements the TrailingGroup definition.',
    info={'definition': 'TrailingGroup'}
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The user's display name."),
    sa.Column('username', sa.String(), nullable=False, comment='The username used to identify the user.'),
    sa.Column('password', sa.String(), nullable=False, comment='The password credential used by the user.'),
    sa.Column('api_key', sa.String(), nullable=False, comment='The API key assigned to the user.'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the user.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Implements the User definition.',
    info={'definition': 'User'}
    )
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The broker's display name."),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='The user who owns the broker configuration.'),
    sa.Column('trading_platform_id', sa.Integer(), nullable=False, comment='The trading platform the broker uses.'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the broker.'),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], name='fk_brokers_trading_platform_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_brokers_user_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_brokers_user_id_name'),
    comment='Implements the Broker definition.',
    info={'definition': 'Broker'}
    )
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brokers_trading_platform_id'), ['trading_platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brokers_user_id'), ['user_id'], unique=False)

    op.create_table('partial_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The partial rule's display name."),
    sa.Column('partial_group_id', sa.Integer(), nullable=False, comment='The partial group that contains the rule.'),
    sa.Column('profit_percentage', sa.Numeric(), nullable=False, comment='The profit percentage that activates the rule.'),
    sa.Column('close_percentage', sa.Numeric(), nullable=False, comment='The percentage of the position closed when the rule activates.'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the partial rule.'),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], name='fk_partial_rules_partial_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Implements the PartialRule definition.',
    info={'definition': 'PartialRule'}
    )
    with op.batch_alter_table('partial_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partial_rules_partial_group_id'), ['partial_group_id'], unique=False)

    op.create_table('trailing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The trailing rule's display name."),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False, comment='The trailing group that contains the rule.'),
    sa.Column('trigger_percentage', sa.Numeric(), nullable=False, comment='The percentage of the take-profit target that, once reached, activates the rule.'),
    sa.Column('take_profit_adjustment', sa.Numeric(), nullable=True, comment='The take-profit adjustment applied when the rule activates.'),
    sa.Column('stop_loss_adjustment', sa.Numeric(), nullable=True, comment='The stop-loss adjustment applied when the rule activates.'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the trailing rule.'),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], name='fk_trailing_rules_trailing_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Implements the TrailingRule definition.',
    info={'definition': 'TrailingRule'}
    )
    with op.batch_alter_table('trailing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trailing_rules_trailing_group_id'), ['trailing_group_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The account's display name."),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='The account group that contains the account.'),
    sa.Column('broker_id', sa.Integer(), nullable=False, comment='The broker that holds the account.'),
    sa.Column('base_currency_id', sa.Integer(), nullable=False, comment='The base currency the account is held in.'),
    sa.Column('username', sa.String(), nullable=False, comment='The username used to access the trading account.'),
    sa.Column('password', sa.String(), nullable=False, comment='The credential used to access the trading account.'),
    sa.Column('leverage', sa.Integer(), nullable=False, comment="The account's leverage multiplier."),
    sa.Column('balance', sa.Numeric(), nullable=False, comment="The account's current balance."),
    sa.Column('account_type', sa.String(), nullable=False, comment='The account model, such as cfd or spread_betting.'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the account.'),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currencies.id'], name='fk_accounts_base_currency_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], name='fk_accounts_broker_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['account_groups.id'], name='fk_accounts_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Implements the Account definition.',
    info={'definition': 'Account'}
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_base_currency_id'), ['base_currency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_broker_id'), ['broker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_group_id'), ['group_id'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The action's display name."),
    sa.Column('action_group_id', sa.Integer(), nullable=False, comment='The action group that contains the action.'),
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='The asset the action trades.'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='The account the action executes through.'),
    sa.Column('partial_group_id', sa.Integer(), nullable=False, comment='The partial group the action applies.'),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False, comment='The trailing group the action applies.'),
    sa.Column('risk_by_reward', sa.Numeric(), nullable=False, comment='The risk-to-reward value the action trades at.'),
    sa.Column('take_profit', sa.Numeric(), nullable=False, comment='The take-profit value the action opens with.'),
    sa.Column('stop_loss', sa.Numeric(), nullable=False, comment='The stop-loss value the action opens with.'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the action.'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_actions_account_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], name='fk_actions_action_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_actions_asset_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], name='fk_actions_partial_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], name='fk_actions_trailing_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Implements the Action definition.',
    info={'definition': 'Action'}
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_action_group_id'), ['action_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_partial_group_id'), ['partial_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_trailing_group_id'), ['trailing_group_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="The position's display name."),
    sa.Column('trading_platform_id', sa.Integer(), nullable=False, comment='The trading platform the position executes on.'),
    sa.Column('broker_id', sa.Integer(), nullable=False, comment='The broker the position executes through.'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='The trading account the position uses.'),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False, comment='The trailing group applied to the position.'),
    sa.Column('partial_group_id', sa.Integer(), nullable=False, comment='The partial group applied to the position.'),
    sa.Column('action_group_id', sa.Integer(), nullable=False, comment='The action group the position belongs to.'),
    sa.Column('action_id', sa.Integer(), nullable=False, comment='The action the position was created from.'),
    sa.Column('date', sa.DateTime(), nullable=False, comment="The position's date and time."),
    sa.Column('volume', sa.Numeric(), nullable=False, comment="The position's trading volume."),
    sa.Column('profit', sa.Numeric(), nullable=False, comment="The position's current profit or loss."),
    sa.Column('is_executed', sa.Boolean(), nullable=False, comment='Indicates whether the position has been executed.'),
    sa.Column('order_type', sa.String(), nullable=False, comment="The position's order type."),
    sa.Column('base_tp', sa.Numeric(), nullable=False, comment='The take-profit value the position opened with.'),
    sa.Column('base_sl', sa.Numeric(), nullable=False, comment='The stop-loss value the position opened with.'),
    sa.Column('real_tp', sa.Numeric(), nullable=False, comment="The position's current take-profit value."),
    sa.Column('real_sl', sa.Numeric(), nullable=False, comment="The position's current stop-loss value."),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Indicates whether the entity is active.'),
    sa.Column('description', sa.String(), nullable=True, comment='Describes the position.'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_positions_account_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], name='fk_positions_action_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='fk_positions_action_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], name='fk_positions_broker_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], name='fk_positions_partial_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], name='fk_positions_trading_platform_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], name='fk_positions_trailing_group_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Implements the Position definition.',
    info={'definition': 'Position'}
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_action_group_id'), ['action_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_broker_id'), ['broker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_partial_group_id'), ['partial_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_trading_platform_id'), ['trading_platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_trailing_group_id'), ['trailing_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_trailing_group_id'))
        batch_op.drop_index(batch_op.f('ix_positions_trading_platform_id'))
        batch_op.drop_index(batch_op.f('ix_positions_partial_group_id'))
        batch_op.drop_index(batch_op.f('ix_positions_broker_id'))
        batch_op.drop_index(batch_op.f('ix_positions_action_id'))
        batch_op.drop_index(batch_op.f('ix_positions_action_group_id'))
        batch_op.drop_index(batch_op.f('ix_positions_account_id'))

    op.drop_table('positions')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_trailing_group_id'))
        batch_op.drop_index(batch_op.f('ix_actions_partial_group_id'))
        batch_op.drop_index(batch_op.f('ix_actions_asset_id'))
        batch_op.drop_index(batch_op.f('ix_actions_action_group_id'))
        batch_op.drop_index(batch_op.f('ix_actions_account_id'))

    op.drop_table('actions')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_group_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_broker_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_base_currency_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('trailing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trailing_rules_trailing_group_id'))

    op.drop_table('trailing_rules')
    with op.batch_alter_table('partial_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partial_rules_partial_group_id'))

    op.drop_table('partial_rules')
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brokers_user_id'))
        batch_op.drop_index(batch_op.f('ix_brokers_trading_platform_id'))

    op.drop_table('brokers')
    op.drop_table('users')
    op.drop_table('trailing_groups')
    op.drop_table('trading_platforms')
    op.drop_table('partial_groups')
    op.drop_table('currencies')
    op.drop_table('assets')
    op.drop_table('action_groups')
    op.drop_table('account_groups')
    # ### end Alembic commands ###
