"""initial_schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-06 01:32:05.437720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_groups')),
    sa.UniqueConstraint('name', name='uq_action_groups_name')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('point_size', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('digits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('name', name='uq_assets_name'),
    sa.UniqueConstraint('symbol', name='uq_assets_symbol')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('decimal_digits', sa.Integer(), server_default='2', nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currencies')),
    sa.UniqueConstraint('code', name='uq_currencies_code')
    )
    op.create_table('partial_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partial_groups')),
    sa.UniqueConstraint('name', name='uq_partial_groups_name')
    )
    op.create_table('trading_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trading_platforms'))
    )
    op.create_table('trailing_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trailing_groups')),
    sa.UniqueConstraint('name', name='uq_trailing_groups_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('name', name='uq_users_name')
    )
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trading_platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], name=op.f('fk_brokers_trading_platform_id_trading_platforms'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_brokers_user_id_users'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brokers')),
    sa.UniqueConstraint('user_id', 'name', name='uq_brokers_user_id_name')
    )
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.create_index('ix_brokers_trading_platform_id', ['trading_platform_id'], unique=False)
        batch_op.create_index('ix_brokers_user_id', ['user_id'], unique=False)

    op.create_table('partial_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('profit_percentage', sa.Numeric(), nullable=False),
    sa.Column('close_percentage', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], name=op.f('fk_partial_rules_partial_group_id_partial_groups'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partial_rules')),
    sa.UniqueConstraint('name', name='uq_partial_rules_name')
    )
    with op.batch_alter_table('partial_rules', schema=None) as batch_op:
        batch_op.create_index('ix_partial_rules_partial_group_id', ['partial_group_id'], unique=False)

    op.create_table('trailing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('trigger_percentage', sa.Numeric(), nullable=False),
    sa.Column('take_profit_adjustment', sa.Numeric(), nullable=True),
    sa.Column('stop_loss_adjustment', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], name=op.f('fk_trailing_rules_trailing_group_id_trailing_groups'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trailing_rules')),
    sa.UniqueConstraint('name', name='uq_trailing_rules_name')
    )
    with op.batch_alter_table('trailing_rules', schema=None) as batch_op:
        batch_op.create_index('ix_trailing_rules_trailing_group_id', ['trailing_group_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('base_currency_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currencies.id'], name=op.f('fk_accounts_base_currency_id_currencies'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], name=op.f('fk_accounts_broker_id_brokers'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('name', name='uq_accounts_name')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_base_currency_id', ['base_currency_id'], unique=False)
        batch_op.create_index('ix_accounts_broker_id', ['broker_id'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('action_group_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('risk_by_reward', sa.Numeric(), nullable=False),
    sa.Column('take_profit', sa.Numeric(), nullable=False),
    sa.Column('stop_loss', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_actions_account_id_accounts'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], name=op.f('fk_actions_action_group_id_action_groups'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_actions_asset_id_assets'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], name=op.f('fk_actions_partial_group_id_partial_groups'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], name=op.f('fk_actions_trailing_group_id_trailing_groups'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions')),
    sa.UniqueConstraint('name', name='uq_actions_name')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index('ix_actions_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_actions_action_group_id', ['action_group_id'], unique=False)
        batch_op.create_index('ix_actions_asset_id', ['asset_id'], unique=False)
        batch_op.create_index('ix_actions_partial_group_id', ['partial_group_id'], unique=False)
        batch_op.create_index('ix_actions_trailing_group_id', ['trailing_group_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trading_platform_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('action_group_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('profit', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('is_executed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('base_tp', sa.Numeric(), nullable=False),
    sa.Column('base_sl', sa.Numeric(), nullable=False),
    sa.Column('real_tp', sa.Numeric(), nullable=False),
    sa.Column('real_sl', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_positions_account_id_accounts'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], name=op.f('fk_positions_action_group_id_action_groups'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_positions_action_id_actions'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], name=op.f('fk_positions_broker_id_brokers'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], name=op.f('fk_positions_partial_group_id_partial_groups'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], name=op.f('fk_positions_trading_platform_id_trading_platforms'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], name=op.f('fk_positions_trailing_group_id_trailing_groups'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('name', name='uq_positions_name')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('ix_positions_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_positions_action_group_id', ['action_group_id'], unique=False)
        batch_op.create_index('ix_positions_action_id', ['action_id'], unique=False)
        batch_op.create_index('ix_positions_broker_id', ['broker_id'], unique=False)
        batch_op.create_index('ix_positions_partial_group_id', ['partial_group_id'], unique=False)
        batch_op.create_index('ix_positions_trading_platform_id', ['trading_platform_id'], unique=False)
        batch_op.create_index('ix_positions_trailing_group_id', ['trailing_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('ix_positions_trailing_group_id')
        batch_op.drop_index('ix_positions_trading_platform_id')
        batch_op.drop_index('ix_positions_partial_group_id')
        batch_op.drop_index('ix_positions_broker_id')
        batch_op.drop_index('ix_positions_action_id')
        batch_op.drop_index('ix_positions_action_group_id')
        batch_op.drop_index('ix_positions_account_id')

    op.drop_table('positions')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index('ix_actions_trailing_group_id')
        batch_op.drop_index('ix_actions_partial_group_id')
        batch_op.drop_index('ix_actions_asset_id')
        batch_op.drop_index('ix_actions_action_group_id')
        batch_op.drop_index('ix_actions_account_id')

    op.drop_table('actions')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_broker_id')
        batch_op.drop_index('ix_accounts_base_currency_id')

    op.drop_table('accounts')
    with op.batch_alter_table('trailing_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_trailing_rules_trailing_group_id')

    op.drop_table('trailing_rules')
    with op.batch_alter_table('partial_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_partial_rules_partial_group_id')

    op.drop_table('partial_rules')
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.drop_index('ix_brokers_user_id')
        batch_op.drop_index('ix_brokers_trading_platform_id')

    op.drop_table('brokers')
    op.drop_table('users')
    op.drop_table('trailing_groups')
    op.drop_table('trading_platforms')
    op.drop_table('partial_groups')
    op.drop_table('currencies')
    op.drop_table('assets')
    op.drop_table('action_groups')
    # ### end Alembic commands ###
