"""initial schema

Revision ID: cd1a640d9d0a
Revises: 
Create Date: 2026-09-11 11:52:21.602430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1a640d9d0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('code', sa.String(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(), autoincrement=False, nullable=False),
    sa.Column('password', sa.String(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.String(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('account_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_account_groups_0')
    )
    op.create_table('action_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_action_groups_0')
    )
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_brokers_0')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.String(), autoincrement=False, nullable=True),
    sa.Column('country', sa.String(), autoincrement=False, nullable=True),
    sa.Column('decimal_digits', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_currencies_0')
    )
    op.create_table('instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('trading_platform_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), autoincrement=False, nullable=True),
    sa.Column('username', sa.String(), autoincrement=False, nullable=True),
    sa.Column('password', sa.String(), autoincrement=False, nullable=True),
    sa.Column('api_key', sa.String(), autoincrement=False, nullable=True),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_instances_0')
    )
    op.create_table('partial_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_partial_groups_0')
    )
    op.create_table('trailing_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_trailing_groups_0')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('base_currency_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), autoincrement=False, nullable=False),
    sa.Column('password', sa.String(), autoincrement=False, nullable=False),
    sa.Column('leverage', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('account_type', sa.String(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['account_groups.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'broker_id', 'instance_id', name='uq_accounts_0'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), autoincrement=False, nullable=False),
    sa.Column('category', sa.String(), autoincrement=False, nullable=False),
    sa.Column('point_size', sa.Float(), autoincrement=False, nullable=False),
    sa.Column('digits', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_id', 'symbol', name='uq_assets_0')
    )
    op.create_table('partial_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('profit_percentage', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('close_percentage', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('partial_group_id', 'profit_percentage', name='uq_partial_rules_0')
    )
    op.create_table('trailing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('trigger_percentage', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('take_profit_adjustment', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('stop_loss_adjustment', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('trailing_group_id', 'trigger_percentage', name='uq_trailing_rules_0')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('action_group_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('risk_by_reward', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], ),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_group_id', 'name', name='uq_actions_0')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('trading_platform_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('action_group_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('profit', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('is_executed', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('order_type', sa.String(), autoincrement=False, nullable=False),
    sa.Column('base_tp', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('base_sl', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('real_tp', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('real_sl', sa.Numeric(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('status', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], ),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], ),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], ),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_table('actions')
    op.drop_table('trailing_rules')
    op.drop_table('partial_rules')
    op.drop_table('assets')
    op.drop_table('accounts')
    op.drop_table('trailing_groups')
    op.drop_table('partial_groups')
    op.drop_table('instances')
    op.drop_table('currencies')
    op.drop_table('brokers')
    op.drop_table('action_groups')
    op.drop_table('account_groups')
    op.drop_table('users')
    op.drop_table('trading_platforms')
    # ### end Alembic commands ###
