"""initial schema

Revision ID: 92befd7b655c
Revises: 
Create Date: 2026-09-10 22:12:48.814543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92befd7b655c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('account_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_account_groups_user_id_name')
    )
    with op.batch_alter_table('account_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_groups_user_id'), ['user_id'], unique=False)

    op.create_table('action_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_action_groups_user_id_name')
    )
    with op.batch_alter_table('action_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_groups_user_id'), ['user_id'], unique=False)

    op.create_table('brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_brokers_user_id_name')
    )
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brokers_user_id'), ['user_id'], unique=False)

    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('decimal_digits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_currencies_user_id_code')
    )
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currencies_user_id'), ['user_id'], unique=False)

    op.create_table('instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trading_platform_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_instances_user_id_name')
    )
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instances_trading_platform_id'), ['trading_platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_user_id'), ['user_id'], unique=False)

    op.create_table('partial_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_partial_groups_user_id_name')
    )
    with op.batch_alter_table('partial_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partial_groups_user_id'), ['user_id'], unique=False)

    op.create_table('trailing_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_trailing_groups_user_id_name')
    )
    with op.batch_alter_table('trailing_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trailing_groups_user_id'), ['user_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('base_currency_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currencies.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['account_groups.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'broker_id', 'instance_id', name='uq_accounts_group_id_broker_id_instance_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_base_currency_id'), ['base_currency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_broker_id'), ['broker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_instance_id'), ['instance_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('point_size', sa.Float(), nullable=False),
    sa.Column('digits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_id', 'symbol', name='uq_assets_broker_id_symbol')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_broker_id'), ['broker_id'], unique=False)

    op.create_table('partial_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('profit_percentage', sa.Numeric(), nullable=False),
    sa.Column('close_percentage', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('partial_group_id', 'profit_percentage', name='uq_partial_rules_partial_group_id_profit_percentage')
    )
    with op.batch_alter_table('partial_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partial_rules_partial_group_id'), ['partial_group_id'], unique=False)

    op.create_table('trailing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('trigger_percentage', sa.Numeric(), nullable=False),
    sa.Column('take_profit_adjustment', sa.Numeric(), nullable=True),
    sa.Column('stop_loss_adjustment', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('trailing_group_id', 'trigger_percentage', name='uq_trailing_rules_trailing_group_id_trigger_percentage')
    )
    with op.batch_alter_table('trailing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trailing_rules_trailing_group_id'), ['trailing_group_id'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('action_group_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('risk_by_reward', sa.Numeric(), nullable=False),
    sa.Column('take_profit', sa.Numeric(), nullable=False),
    sa.Column('stop_loss', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_group_id', 'name', name='uq_actions_action_group_id_name')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_action_group_id'), ['action_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_partial_group_id'), ['partial_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_trailing_group_id'), ['trailing_group_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trading_platform_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('action_group_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('profit', sa.Numeric(), nullable=False),
    sa.Column('is_executed', sa.Boolean(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('base_tp', sa.Numeric(), nullable=False),
    sa.Column('base_sl', sa.Numeric(), nullable=False),
    sa.Column('real_tp', sa.Numeric(), nullable=False),
    sa.Column('real_sl', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_group_id'], ['action_groups.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_action_group_id'), ['action_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_broker_id'), ['broker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_partial_group_id'), ['partial_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_trading_platform_id'), ['trading_platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_trailing_group_id'), ['trailing_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_user_id'))
        batch_op.drop_index(batch_op.f('ix_positions_trailing_group_id'))
        batch_op.drop_index(batch_op.f('ix_positions_trading_platform_id'))
        batch_op.drop_index(batch_op.f('ix_positions_partial_group_id'))
        batch_op.drop_index(batch_op.f('ix_positions_broker_id'))
        batch_op.drop_index(batch_op.f('ix_positions_action_id'))
        batch_op.drop_index(batch_op.f('ix_positions_action_group_id'))
        batch_op.drop_index(batch_op.f('ix_positions_account_id'))

    op.drop_table('positions')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_trailing_group_id'))
        batch_op.drop_index(batch_op.f('ix_actions_partial_group_id'))
        batch_op.drop_index(batch_op.f('ix_actions_asset_id'))
        batch_op.drop_index(batch_op.f('ix_actions_action_group_id'))
        batch_op.drop_index(batch_op.f('ix_actions_account_id'))

    op.drop_table('actions')
    with op.batch_alter_table('trailing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trailing_rules_trailing_group_id'))

    op.drop_table('trailing_rules')
    with op.batch_alter_table('partial_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partial_rules_partial_group_id'))

    op.drop_table('partial_rules')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_broker_id'))

    op.drop_table('assets')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_instance_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_group_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_broker_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_base_currency_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('trailing_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trailing_groups_user_id'))

    op.drop_table('trailing_groups')
    with op.batch_alter_table('partial_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partial_groups_user_id'))

    op.drop_table('partial_groups')
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instances_user_id'))
        batch_op.drop_index(batch_op.f('ix_instances_trading_platform_id'))

    op.drop_table('instances')
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currencies_user_id'))

    op.drop_table('currencies')
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brokers_user_id'))

    op.drop_table('brokers')
    with op.batch_alter_table('action_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_groups_user_id'))

    op.drop_table('action_groups')
    with op.batch_alter_table('account_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_groups_user_id'))

    op.drop_table('account_groups')
    op.drop_table('users')
    op.drop_table('trading_platforms')
    # ### end Alembic commands ###
