"""Storage Service Interface: Logic's internal gateway to every Database capability."""

from database.interface import (
    CommandResult,
    ConfigurationError,
    ConnectionFailureError,
    DatabaseError,
    DatabaseInstance,
    DeclarationMismatchError,
    ExecutionError,
    Filter,
    FilterCombination,
    FilterOperator,
    InactiveInstanceError,
    InvalidInputError,
    LifecycleError,
    LifecycleResult,
    Order,
    OrderDirection,
)

from logic.services.storage.actions import (
    storage_add,
    storage_count,
    storage_create_tables,
    storage_delete,
    storage_disable,
    storage_enable,
    storage_execute_command,
    storage_get_by_id,
    storage_insert_initial_data,
    storage_list,
    storage_max,
    storage_min,
    storage_prepare,
    storage_sum,
    storage_truncate,
    storage_update,
)
from logic.services.storage.naming import verify_exports as _verify_exports

__all__ = [
    "CommandResult",
    "ConfigurationError",
    "ConnectionFailureError",
    "DatabaseError",
    "DatabaseInstance",
    "DeclarationMismatchError",
    "ExecutionError",
    "Filter",
    "FilterCombination",
    "FilterOperator",
    "InactiveInstanceError",
    "InvalidInputError",
    "LifecycleError",
    "LifecycleResult",
    "Order",
    "OrderDirection",
    "storage_add",
    "storage_count",
    "storage_create_tables",
    "storage_delete",
    "storage_disable",
    "storage_enable",
    "storage_execute_command",
    "storage_get_by_id",
    "storage_insert_initial_data",
    "storage_list",
    "storage_max",
    "storage_min",
    "storage_prepare",
    "storage_sum",
    "storage_truncate",
    "storage_update",
]

_verify_exports(__all__)
