"""initial

Revision ID: 7294d37eb142
Revises: 
Create Date: 2026-09-02 13:33:34.676049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7294d37eb142'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partial_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('risk_parameter', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trailing_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trading_platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trading_platform_id'], ['trading_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brokers_trading_platform_id'), ['trading_platform_id'], unique=False)

    op.create_table('partial_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('partial_group_id', sa.Integer(), nullable=False),
    sa.Column('profit_threshold', sa.Float(), nullable=False),
    sa.Column('close_portion', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['partial_group_id'], ['partial_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partial_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partial_rules_partial_group_id'), ['partial_group_id'], unique=False)

    op.create_table('trailing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trailing_group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trailing_group_id'], ['trailing_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trailing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trailing_rules_trailing_group_id'), ['trailing_group_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_broker_id'), ['broker_id'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['action_groups.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('executes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('executes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executes_action_id'), ['action_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executes_action_id'))

    op.drop_table('executes')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_actions_group_id'))
        batch_op.drop_index(batch_op.f('ix_actions_asset_id'))
        batch_op.drop_index(batch_op.f('ix_actions_account_id'))

    op.drop_table('actions')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_broker_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('trailing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trailing_rules_trailing_group_id'))

    op.drop_table('trailing_rules')
    with op.batch_alter_table('partial_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partial_rules_partial_group_id'))

    op.drop_table('partial_rules')
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brokers_trading_platform_id'))

    op.drop_table('brokers')
    op.drop_table('trailing_groups')
    op.drop_table('trading_platforms')
    op.drop_table('strategies')
    op.drop_table('positions')
    op.drop_table('partial_groups')
    op.drop_table('assets')
    op.drop_table('action_groups')
    # ### end Alembic commands ###
