engines:
  sqlite:
    name: SQLite
    driver: sqlite3
    parameters:
      foreign_keys: true
      check_same_thread: false
  postgresql:
    name: PostgreSQL
    driver: psycopg
    parameters: {}
instances:
  sqlite:
    name: SQLite
    active: true
    purpose: Default application data.
    engine: sqlite
    database: application.db
    host: ''
    port: ''
    path: db/application.db
    username: ''
    password: ''
    parameters: {}
  postgresql:
    name: PostgreSQL
    active: true
    purpose: Application data on PostgreSQL.
    engine: postgresql
    database: application
    host: 127.0.0.1
    port: '5432'
    path: ''
    username: postgres
    password: ''
    parameters: {}
settings:
  default_instance: sqlite
  parameters:
    filter_combination: AND
    default_limit: -1
    default_order:
      field: id
      direction: ascending
