"""The contract every Instance implementation fulfils, as seen by Core."""

import builtins
from collections.abc import Mapping, Sequence
from typing import Any, Protocol

from database.core._contracts import Query

Record = dict[str, Any]


class Engine(Protocol):
    """One complete Instance implementation: every Entity Operation, ExecuteCommand,
    and the capabilities both Lifecycle Commands need."""

    def add(self, entity: str, values: Mapping[str, Any]) -> Record: ...

    def update(
        self, entity: str, identifier: int, values: Mapping[str, Any]
    ) -> Record | None: ...

    def list(self, entity: str, query: Query) -> builtins.list[Record]: ...

    def delete(self, entity: str, identifier: int) -> Record | None: ...

    def enable(self, entity: str, identifier: int) -> Record | None: ...

    def disable(self, entity: str, identifier: int) -> Record | None: ...

    def get_by_id(self, entity: str, identifier: int) -> Record | None: ...

    def count(self, entity: str, query: Query) -> int: ...

    def sum(self, entity: str, field: str, query: Query) -> Any: ...

    def min(self, entity: str, field: str, query: Query) -> Any: ...

    def max(self, entity: str, field: str, query: Query) -> Any: ...

    def truncate(self, entity: str) -> int: ...

    def execute_command(
        self, command: str, parameters: Mapping[str, Any]
    ) -> tuple[builtins.list[Record] | None, int | None, builtins.list[str] | None]: ...

    def create_tables(self) -> int: ...

    def missing_tables(self) -> builtins.list[str]: ...

    def insert_missing(
        self, records: Sequence[tuple[str, Mapping[str, Any]]]
    ) -> int: ...
