title: Target API
description: ''
key: 7yaU2i9d-1iTpisLDooeaGwz5sUedw_c
host: 127.0.0.1
port: 8000
workers: 2
transport_protocol: HTTP
url: http://127.0.0.1:8000/7yaU2i9d-1iTpisLDooeaGwz5sUedw_c
documentation:
  swagger: http://127.0.0.1:8000/7yaU2i9d-1iTpisLDooeaGwz5sUedw_c/docs
  redoc: http://127.0.0.1:8000/7yaU2i9d-1iTpisLDooeaGwz5sUedw_c/redoc
